name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version number
        run: |
          TAG=$(echo "${GITHUB_REF#refs/tags/}" | sed 's/^v//')
          echo "TAG=$TAG" >> $GITHUB_ENV

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
  
      - run: make
        env:
          GOOS: linux
          GOARCH: amd64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: oci-add-hooks
          body: "Release of oci-add-hooks version ${{ env.TAG }}"
          draft: false
          prerelease: false
